version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - node-app
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - "4000:4000"
    # env_file:
    #   - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db: